<template>

    <form action="#">

        <fieldset class="_main-field">

            <legend>Настройки:</legend>

            <label v-for="(r, key) in ranges">
                <input type="range" :min="r.min" :max="r.max" step="1" :name="key" v-model="r.value">
                <p class="range-label">{{ r.name }} {{ r.value }}</p>
            </label>

            <fieldset>
                <legend>Операции:</legend>
                <div class="control-group">
                    <label v-for="(oper, key) in operations" class="control control-checkbox">
                        {{ oper.name }}
                        <input type="checkbox" :name="key" v-model="oper.checked">
                        <div class="control_indicator"></div>
                    </label>
                </div>
            </fieldset>

        </fieldset>
    </form>

</template>

<script>
    export default {
        name: "settings-form",
        data: function () {
            return {
                ranges: {
                    duration: {
                        name: 'Длительность (мин): ',
                        value: 5,
                        min: 1,
                        max: 10
                    },
                    difficulty: {
                        name: 'Сложность: ',
                        value: 5,
                        min: 1,
                        max: 10
                    }
                },
                operations: {
                    summ: {
                        name: 'Сложение',
                        checked: false
                    },
                    sub: {
                        name: 'Вычетание',
                        checked: false
                    },
                    mult: {
                        name: 'Умножение',
                        checked: false
                    },
                    dev: {
                        name: 'Деление',
                        checked: false
                    },
                    pow: {
                        name: 'Возведение в степень',
                        checked: false
                    }
                }
            }
        }
    }
</script>

<style scoped>

    fieldset {
        border: 1px solid lightblue;
        -webkit-margin-start: 0;
        -webkit-margin-end: 0;
        -webkit-padding-before: 0.35em;
        -webkit-padding-start: 0.75em;
        -webkit-padding-end: 0.75em;
        -webkit-padding-after: 0.625em;
        margin: 15px auto;
    }

    ._main-field {
        padding: 25px;
    }

    /* Контейнер ползунка*/

    .range-label {
        text-align: center;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
    }

    input[type=range] {
        -webkit-appearance: none;
        height: 15px;
        width: 100%;
    }

    input[type=range]:focus {
        outline: none;
    }

    /* Полоса в Хроме */

    input[type=range]::-webkit-slider-runnable-track {
        cursor: pointer;
        border: 1px solid lightblue;
        background: #AD020D;
        height: 1px;
    }

    /* Бегунок */
    input[type=range]::-webkit-slider-thumb {
        border: 7px solid transparent; /* Прозрачные границы */
        border-bottom: 7px solid lightblue; /* Добавляем треугольник */
        height: 22px;
        width: 7px;
        cursor: pointer;
        -webkit-appearance: none;
        margin-top: -14px;
    }

    /*
        Generated by:
        http://doodlenerd.com/html-control/css-checkbox-generator
    */

    .control {
        display: block;
        position: relative;
        padding-left: 30px;
        margin-bottom: 5px;
        padding-top: 3px;
        cursor: pointer;
    }

    .control input {
        position: absolute;
        z-index: -1;
        opacity: 0;
    }

    .control_indicator {
        position: absolute;
        top: 2px;
        left: 0;
        height: 20px;
        width: 20px;
        background: #e6e6e6;
        border: 0 solid #000000;
    }

    .control-radio .control_indicator {
        border-radius: 0;
    }

    .control:hover input ~ .control_indicator,
    .control input:focus ~ .control_indicator {
        background: #cccccc;
    }

    .control input:checked ~ .control_indicator {
        background: #2aa1c0;
    }

    .control:hover input:not([disabled]):checked ~ .control_indicator,
    .control input:checked:focus ~ .control_indicator {
        background: #0e6647d;
    }

    .control input:disabled ~ .control_indicator {
        background: #e6e6e6;
        opacity: 0.6;
        pointer-events: none;
    }

    .control_indicator:after {
        box-sizing: unset;
        content: '';
        position: absolute;
        display: none;
    }

    .control input:checked ~ .control_indicator:after {
        display: block;
    }

    .control-checkbox .control_indicator:after {
        left: 8px;
        top: 4px;
        width: 3px;
        height: 8px;
        border: solid #ffffff;
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
    }

    .control-checkbox input:disabled ~ .control_indicator:after {
        border-color: #7b7b7b;
    }

</style>